#!/bin/bash
set -e

stty sane 2>/dev/null || true
printf "\033[K"

# Configure local application workspace filesystem registries
export HOME="${HOME}"
export GAIA_HOME="${HOME}/.gaia"
export GAIA_ALLOW_ORIGINS="*"
export PYTHONWARNINGS="default"
export PYTHONNOUSERSITE=1

# The officially supported updater suppression hooks
export GAIA_DISABLE_UPDATE=1
export GAIA_DISABLE_UPDATE_CHECK="true"

# FORCE UV PIP BEST-MATCH REPOSITORY STRATEGY
export UV_INDEX_STRATEGY="unsafe-best-match"
export UV_EXTRA_INDEX_URL="https://pypi.org/simple"

# Specify TMPDIR needed for appindicator
export TMPDIR=$XDG_RUNTIME_DIR

# 🎯 THE UNIVERSAL PORTABLE PATCH INJECTOR
# We append the read-only snap environment folder to PYTHONPATH.
# This forces whichever Python interpreter GAIA launches (host or snap)
# to load our sitecustomize memory hook on boot automatically!
export PYTHONPATH="${SNAP}/lib/python_patches:${PYTHONPATH}"

# Append the self-contained python execution path cleanly to top-level shells
export PATH="${SNAP}/venv/bin:${SNAP}/usr/bin:${PATH}:/usr/bin:/bin"

RAW_LLM_URL=$(snapctl get backend.url)
if [ -z "$RAW_LLM_URL" ]; then
    RAW_LLM_URL="http://127.0.0.1:13305"
fi

export GAIA_LLM_URL="${RAW_LLM_URL}"
export LEMONADE_BASE_URL="${RAW_LLM_URL}/api/v1"

echo "INFO: Classic Mode: Directing outbound AI model traffic to target server layout: ${GAIA_LLM_URL}"

for service in openai anthropic groq tavily serper; do
    VAL=$(snapctl get "keys.${service}")
    if [ -n "$VAL" ]; then
        case "$service" in
            openai)    export OPENAI_API_KEY="$VAL" ;;
            anthropic) export ANTHROPIC_API_KEY="$VAL" ;;
            groq)      export GROQ_API_KEY="$VAL" ;;
            tavily)    export TAVILY_API_KEY="$VAL" ;;
            serper)    export SERPER_API_KEY="$VAL" ;;
        esac
    fi
done

# set max-steps for Gaia workflows
MAX_STEPS=$(snapctl get backend.maxsteps)
if [ -z "$MAX_STEPS" ]; then
    MAX_STEPS=20
fi
export GAIA_MAX_STEPS="${MAX_STEPS}"
echo "[CONFIG] Set max-steps to $GAIA_MAX_STEPS "

export HTTP_USER_AGENT="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36"
export REBUILD_USER_AGENT="${HTTP_USER_AGENT}"

TARGET_EXEC=$(find "$SNAP/opt/GAIA" -maxdepth 1 -type f -executable | head -n 1)
if [ -z "$TARGET_EXEC" ]; then
    echo "ERROR: Failed to locate core executable launcher binary inside packaged opt footprint tree." >&2
    exit 1
fi

# =====================================================================
# FORCE WORKSPACE STATE OVERRIDE & HISTORICAL PYTHON BRIDGES
# =====================================================================
echo "LOG: Synchronizing local workspace sentinel states..."

if [ -z "$SNAP_VERSION" ]; then
    SNAP_VERSION="0.20.0"
fi

# ---------------------------------------------------------------------
# DEFENSIVE SAFETY SHIELD: Absolute mitigation against system chown loops
# ---------------------------------------------------------------------
if [ "$(id -u)" -ne 0 ]; then
    # Verify GAIA_HOME is explicitly set, is not empty, and points safely within a subfolder
    if [ -n "${GAIA_HOME}" ] && [ "${GAIA_HOME}" != "/" ] && [ "${GAIA_HOME}" != "/home" ]; then
        echo "LOG: Enforcing host profile user ownership claims safely..."
        sudo chown -R "$(id -u):$(id -g)" "${GAIA_HOME}" 2>/dev/null || true
    else
        echo "ERROR: GAIA_HOME target path is invalid or unbound! Aborting ownership sync to protect host."
        exit 1
    fi
fi

# Clear out old proxy nodes safely now that we know GAIA_HOME is locked and secure
rm -rf "${GAIA_HOME}/venv"
mkdir -p "${GAIA_HOME}/venv/bin"

# 1. Write the sentinel state record using the live version token
cat << EOF > "${GAIA_HOME}/electron-install-state.json"
{
  "status": "ready",
  "version": "${SNAP_VERSION}"
}
EOF

# 2. THE HISTORICAL FIX + DYNAMIC PORT GATING:
# Intercepts the dynamic port generated by Electron, kicks off the real python backend,
# and waits for that specific socket to settle active before resolving the execution thread!
cat << EOF > "${GAIA_HOME}/venv/bin/gaia"
#!/bin/bash
if [ "\$1" = "--version" ]; then
    echo "${SNAP_VERSION}"
    exit 0
fi

# Smart Port Sync: If launching the UI chat server, find the dynamic port
if [ "\$1" = "chat" ]; then
    DYNAMIC_PORT=34681 # Default fallback

    # Iterate arguments to find Electron's randomly assigned port value
    args=(\"\$@\")
    for ((i=0; i<\${#args[@]}; i++)); do
        if [ "\${args[i]}" = "--ui-port" ]; then
            DYNAMIC_PORT=\${args[i+1]}
        fi
    done

    # Run the real python server process as a background sub-shell
    "${SNAP}/venv/bin/python3" "${SNAP}/venv/bin/gaia" "\$@" &
    BACKEND_PID=\$!

    # Hold the execution thread until the dynamic socket registers live
    timeout=40
    while ! nc -z 127.0.0.1 \$DYNAMIC_PORT && [ \$timeout -gt 0 ]; do
        sleep 0.2
        timeout=\$((timeout - 1))
    done

    # Hand the tracked background process back over to the main execution chain
    wait \$BACKEND_PID
    exit \$?
fi

# Standard pass-through for secondary asset checks
exec